name: "Materialize dbt action"
description: "Run dbt-materialize commands directly in your Github repo"
author: "Bobby Iliev"

inputs:
  dbt_command:
    description: "dbt command"
    default: "dbt debug"
    required: true
outputs:
  result:
    description: "Success or failure of the dbt command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dbt_command }}
branding:
  icon: 'database'
  color: 'purple'
