name: Materialize dbt action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Materialize dbt action
      uses: bobbyiliev/materialize-dbt-action@main
      with:
        dbt_command: "dbt --version"
      env:
        DBT_MZ_VERSION: 1.3.4
        MZ_PASS: ${{ secrets.MZ_PASS }}
        MZ_USER: ${{ secrets.MZ_USER }}
        MZ_HOST: ${{ secrets.MZ_HOST }}
        MZ_DATABASE: materialize
        MZ_CLUSTER: default
        DBT_PROJECT_DIR: ${{ env.DBT_PROJECT_DIR }}
